[workspace]
members = [
    "matching-engine",
    "schema"
]

[workspace.dependencies]
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["full"] }
prost = "0.11.9"
prost-derive = "0.11.9"
rust_decimal = "1.32.0"
